### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by AgentAntelope** [leejarvis/block-travel#7]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/felltir/.atom/packages/block-travel/lib/block-travel.coffee:38:9)
```

**Comment by leejarvis** [comment]
Thanks for the report. I no longer use Atom so really it's difficult to support this plugin. I'd be happy to add someone who's prepared to maintain it. I'm quite surprise that this hasn't been baked into Atom since 1.0 was recently announced.

**Comment by AgentAntelope** [comment]
Yes, that's pretty surprising to me as well. I'll have a read of this more closely when I'm not busy, and see if I think I can handle it.

**Comment by hmatsuda** [comment]
version 1.0.2 addressed this issue. Please upgrade to this package.

Thanks!
